version: "3"
services:

    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./data/mysql:/var/lib/mysql
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            MYSQL_DATABASE: glpi
            MYSQL_ROOT_PASSWORD: ChangeThis
            MYSQL_USER: glpi
            MYSQL_PASSWORD: changethis
            TZ: America/Sao_Paulo
            
    php:
        image: lamasbr/php-glpi:7.2-fpm
        build: ./php-glpi
        volumes:
            - ./data/glpi:/code
            - ./data/logs:/var/log/nginx
        depends_on:
            - database
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            TZ: America/Sao_Paulo
    
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./data/glpi:/code
            - ./nginx/glpi.temp:/etc/nginx/conf.d/glpi.temp
        depends_on:
            - php
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            NGINX_PORT: 80
            NGINX_SERVER_NAME: glpi.domain.com
            TZ: America/Sao_Paulo
        command: >
            /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
            < /etc/nginx/conf.d/glpi.temp 
            > /etc/nginx/conf.d/default.conf 
            && sed -ri 's/^nginx:x:101:101:/nginx:x:1000:50:/' /etc/passwd && exec nginx -g 'daemon off;'"